# Generated by Django 5.2.4 on 2025-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('posicao', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos_jogadores/')),
            ],
        ),
    ]
