# Generated by Django 5.2.4 on 2025-09-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='noticias/')),
            ],
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(upload_to='jogadores/'),
        ),
    ]
