# Generated by Django 5.2.4 on 2025-09-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_alter_jogador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('historia', models.TextField()),
                ('imagem', models.ImageField(upload_to='index/')),
            ],
        ),
    ]
