# Generated by Django 5.2.4 on 2025-09-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(upload_to='posts/', verbose_name='Imagem')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
            ],
        ),
    ]
